### ISSUE TITLE
css is undefined

### ISSUE THREAD

**Issue by nathany** [rehandalal/flask-funnel#9]
There are no import statements in the documentation anywhere, so I'm not totally sure how Flask-Funnel is loaded. It seems like it's not:

```
    {{ css('styles') }}
UndefinedError: 'css' is undefined
```

**Comment by rehandalal** [comment]
Thanks for pointing that out Nathan, I'll update the docs shortly.

You need to do something like :

``` python
from flask import Flask
from flask.ext.funnel import Funnel

app = Flask(__name__)
Funnel(app)
```

**Comment by rehandalal** [comment]
Fixed.
